version: '3.3'
services:
   db:
     image: mysql:5.7
     restart: always
     dns:
       - 8.8.8.8
       - 8.8.4.4
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
     networks:
       - testnet1

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
     networks:
       - testnet1
       - testnet2

networks:
  testnet1:
    driver: bridge
  testnet2:
    driver: bridge
