apiVersion: v1
kind: Pod
metadata:
  name: primerpod
spec:
  containers:
    - name: myapache
      image: httpd
      ports:
      - containerPort: 80
    - name: mimaria
      image: mariadb
      env:
      - name: MYSQL_ROOT_PASSWORD
        value: "123456"
      ports:
      - containerPort: 3306
