apiVersion: v1
kind: Pod
metadata:
  name: my-app
  labels:
    app: MyApp
spec:
  containers:
  - name: frontend
    image: richardqa/test-python:v1
  - name: redis
    image: redis:alpine
    ports:
    - containerPort: 5000
    - containerPort: 6379
