apiVersion: v1
kind: Pod
metadata:
  name: emptydir
spec:
  volumes:
  - name: test
    emptyDir: {}
  containers:
  - image: busybox
    name: busy
    command: ["sleep", "3600"]  
    volumeMounts:
    - mountPath: /busy
      name: test
  - image: busybox
    name: box
    command: ["sleep", "3600"]  
    volumeMounts:
    - mountPath: /box
      name: test
