apiVersion: v1
kind: Pod
metadata:
  name: my-app
spec:
  containers:
  - name: web
    image: nextcloud:apache
  - name: backend
    image: mariadb
    ports:
    - containerPort: 80
    - containerPort: 3306
