apiVersion: v1
kind: Pod
metadata:
  name: my-app
  labels:
    app: web
spec:
  containers:
  - name: front-end
    image: nextcloud:apache
  - name: backend
    image: mariadb
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: "123456"
    ports:
    - containerPort: 80
    - containerPort: 3306
