apiVersion: v1
kind: Pod
metadata:
  name: my-app2
spec:
  containers:
  - name: frontend
    image: nextcloud:apache
    ports:
    - containerPort: 80
  - name: backend
    image: mariadb
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: "123456"
    ports:
    - containerPort: 3306
