kind: Deployment
apiVersion: apps/v1
metadata:
  name: mydeployapp
spec:
  replicas: 4
  selector:
    matchLabels:
      role: web
  template:
    metadata:
      name: web
      labels:
        role: web
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
          - containerPort: 80
      - name: postgres
        image: postgres:9.5
        ports:
          - containerPort: 5432
