kind: Deployment
apiVersion: apps/v1
metadata:
  name: mydeployapp2
spec:
  selector:
    matchLabels:
      role: web2
  template:
    metadata:
      name: template-web2
      labels:
        role: web2
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
          - containerPort: 80
      - name: postgres
        image: postgres:9.5
        env:
        - name: POSTGRES_PASSWORD
          value: "123456"
        ports:
          - containerPort: 5432
